"""initial

Revision ID: 4564aa576733
Revises: 
Create Date: 2026-03-08 00:01:27.434488

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4564aa576733'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
